commvault_storageaccount="mcdpostnonprodstorage"
commvault_container_name="linuxagents"
commvault_blob_name="CommvaultLinuxAgentInstaller-11.el7_9.x86_64.rpm"
sentinel_storageaccount="mcdpostnonprodstorage"
sentinel_container_name="mcdantivirus-sentinal"
sentinel_storageblobname="SentinelAgent-Linux.zip"
pp_container="scripts"
