name: 'conversion'

on:
  push:
    branches:
    - hcl2yml
    paths-ignore:
    - 'README.md'

jobs:
  hcl2yml:
    name: 'hcl2yml'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    
    # The type of runner that the job will run on
    - name: Download Azure Dependencies Modules
      uses: azure/powershell@v1
      with:
          inlineScript: | 
                Install-Module -Name Az.Compute -Force -AllowClobber
                Install-Module -Name Az.Storage -Force -AllowClobber
                Install-Module -Name Az.Network -Force -AllowClobber
                Install-Module PowerShell-yaml -Force -AllowClobber
                Get-Command -Module PowerShell-yaml
                #convert-os.ps1
                #Read the YAML file using Get-Content and convert the data to a hashtable using ConvertFrom-Yaml. The $os_list variable stores the hashtable object.
                $os_list = (Get-Content -Path "./File/terraform.yml" | ConvertFrom-Yaml)
                #Convert the hashtable object in the $os_list variable to JSON format using ConvertTo-Json. Once in JSON, save the save to C:\temp\PowerShell_operating-systems.json file using Set-Content.
                Set-Content -Path "./File/terraform.json" -Value ($os_list | ConvertTo-Json)
          azPSVersion: '5.0.0'
      
      
